### ISSUE TITLE
integrate uncertainty function

### ISSUE THREAD

**Issue by emmanuel-dubois** [gwrecharge/rechaRge#26]
Create a new function for uncertainty in simulated variables (simulated water budget).

The goal of this function is to run HB with an ensemble of n set of calibrated parameters (let's say the 20 best parameter sets) to simulate a water budget with each parameter set on the same time period.

The function needs to have as input a table containing the n best parameter sets with the best parameter set first.
![image](https://github.com/gwrecharge/rechaRge/assets/118429693/9c275e90-63b8-4348-9ba6-0db114aa0086)

The function need to run the model (HB in our case) with each parameter set on the same period to obtain 20 water budget (step 1). Each water budget need to be aggregated in a non spatial way by averaging the monthly values of all the cells into a single value for each variable of the water budget (VI, runoff, aet, gwr, runoff_2) (step 2). the mean and standard deviation (sd) need to be calculated for each variable using the 20 versions of the same variable, and for each month (step 2). At the end, the function should return a water budget containing for each variable of the water budget the value simulated with the best parameter set, the average value and the sd (3 columns for each variable) (step 3). The final data table should then consist of 20 columns (year, month, vi_1, vi_mean, vi_sd, ... , gwr_1, gwr_mean, gwr_sd).
![image](https://github.com/gwrecharge/rechaRge/assets/118429693/ca025c70-ea5f-4d57-9960-1a1f075a07f4)

**Comment by ymarcon** [comment]
![image](https://github.com/gwrecharge/rechaRge/assets/2581149/a1979a12-3902-468c-a0e6-a07c5b9552fb)

**Comment by ymarcon** [comment]
Uncertainty plots added to the online book:
https://gwrecharge.github.io/rechaRge-book/calibration-and-sensitity.html#evaluate-uncertainty
